name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
      - 
        name: Build project
        run: |
          mkdir build
          cd build
          cmake -G "Unix Makefiles" -D "CMAKE_TOOLCHAIN_FILE=../tools/CMake/GNU-ARM-Toolchain.cmake" ../
          make -j

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/*