name: ci

on:
  push:
    branches:
      - "windows-latest"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
      - 
        name: Build project
        run: |
          .\build.bat
          .\clean.bat

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/*